{
    "name": "Hỗ trợ khách hàng",
    "summary": "Quản lý ticket yêu cầu hỗ trợ trên Odoo 19",
    "version": "19.0.1.0.0",
    "category": "Dịch vụ/Hỗ trợ khách hàng",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/security.xml",
        "security/rules.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/helpdesk_stage_data.xml",
        "views/helpdesk_stage_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_partner_views.xml",
        "views/helpdesk_user_views.xml",
        "wizard/helpdesk_assign_wizard_views.xml",
        "wizard/helpdesk_agent_create_wizard_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
